### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by tavurth** [nathancahill/aws-serverless-micro#1]
```javascript
{
  "errorType": "TypeError",
  "errorMessage": "Cannot convert undefined or null to object",
  "trace": [
    "TypeError: Cannot convert undefined or null to object",
    "    at Function.keys (<anonymous>)",
    "    at mapApiGatewayEventToHttpRequest (/var/task/node_modules/aws-serverless-micro/index.js:26:12)",
    "    at Runtime.handler (/var/task/node_modules/aws-serverless-micro/index.js:72:17)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:63:25)",
    "    at process._tickCallback (internal/process/next_tick.js:68:7)"
  ]
}
```

From the simple:

```js
module.exports = {
  main: require('aws-serverless-micro')(require('./src/index')),
};
```

```js
const compress = require('micro-compress');

const { compose } = require('rambda');
const { handleErrors } = require('micro-boom');

function main(req, res) {
  return send(res, 200, 'Hello from micro');
}

module.exports = compose(
  // Enable gzip compression for results
  // github.com/joakimbeng/micro-compress
  compress,

  // Handle errors with BOOM response
  // github.com/onbjerg/micro-boom
  handleErrors,
)(main);
```

<img width="1121" alt="Screenshot 2019-08-02 at 23 47 15" src="https://user-images.githubusercontent.com/100964/62385694-f5c03800-b57f-11e9-9754-6da1acc93dfd.png">

Any ideas?

**Comment by tavurth** [comment]
Hmm, the functions seem to work when called via browser. They fail when called via the AWS lambda test spawner. (Inside AWS console)

Perhaps it's their bug, feel free to close this if you can't reproduce.

**Comment by nathancahill** [comment]
Yes, this specifically converts AWS API Gateway events to micro. It will not work for other events, since there is no HTTP event to pass.
